import { TisParameters, EmployeeInput } from '../types';

export const TURKISH_MONTHS = [
  'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
  'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
];

export const DEFAULT_TIS_TEMPLATES: Record<string, TisParameters> = {
  kamu: {
    id: 'kamu',
    name: 'Kamu Çerçeve TİS (İşçi)',
    description: 'Kamuda sürekli işçiler için geçerli çerçeve anlaşması modeli (60 gün ikramiye, kıdem primi, gece zammı, bayram harçlığı)',
    year: 2025,
    minimumWageGross: 26005.50,
    sgkCeilingMultiplier: 7.5,
    sgkEmployeeRate: 0.14,
    unemploymentEmployeeRate: 0.01,
    sgkEmployerRate: 0.205,
    unemploymentEmployerRate: 0.02,
    employerIncentive5Percent: true,
    stampTaxRate: 0.00759,
    taxBrackets: [
      { limit: 158000, rate: 0.15 },
      { limit: 330000, rate: 0.20 },
      { limit: 800000, rate: 0.27 },
      { limit: 4300000, rate: 0.35 },
      { limit: Infinity, rate: 0.40 },
    ],
    foodAidDailyExemption: 240.00,
    childAidExemptionPercent: 0.04,
    familyAidExemptionPercent: 0.10,
    normalOvertimeMultiplier: 1.60,
    weekendOvertimeMultiplier: 2.00,
    holidayOvertimeMultiplier: 3.00,
    nightShiftAllowanceRate: 0.15,
    seniorityPayPerYear: 18.50, // Günlük yevmiyeye eklenen TL (yıl başına)
    defaultMonthlyFuelAid: 1500,
    defaultDailyFoodAid: 260,
    defaultMonthlyTransportAid: 1800,
    defaultFamilyAidAmount: 1200,
    defaultChildAidPerChild: 350,
    defaultHygieneClothingAid: 850,
    annualBonusDaysTotal: 60,
    bonusMonths: [3, 6, 9, 12],
    bonusDailyMultiplier: 1.0,
    unionDuesDays: 1,
    unionDuesPercentFallback: 0.0333,
  },
  belediye: {
    id: 'belediye',
    name: 'Belediye / İştirak TİS Modeli',
    description: 'Belediye şirketleri ve yerel yönetim TİS modeli (112 gün ikramiye, yüksek sosyal yardım, nakdi yemek ve yol)',
    year: 2025,
    minimumWageGross: 26005.50,
    sgkCeilingMultiplier: 7.5,
    sgkEmployeeRate: 0.14,
    unemploymentEmployeeRate: 0.01,
    sgkEmployerRate: 0.205,
    unemploymentEmployerRate: 0.02,
    employerIncentive5Percent: true,
    stampTaxRate: 0.00759,
    taxBrackets: [
      { limit: 158000, rate: 0.15 },
      { limit: 330000, rate: 0.20 },
      { limit: 800000, rate: 0.27 },
      { limit: 4300000, rate: 0.35 },
      { limit: Infinity, rate: 0.40 },
    ],
    foodAidDailyExemption: 240.00,
    childAidExemptionPercent: 0.04,
    familyAidExemptionPercent: 0.10,
    normalOvertimeMultiplier: 1.70,
    weekendOvertimeMultiplier: 2.50,
    holidayOvertimeMultiplier: 3.50,
    nightShiftAllowanceRate: 0.12,
    seniorityPayPerYear: 22.00,
    defaultMonthlyFuelAid: 1800,
    defaultDailyFoodAid: 280,
    defaultMonthlyTransportAid: 2100,
    defaultFamilyAidAmount: 1400,
    defaultChildAidPerChild: 450,
    defaultHygieneClothingAid: 1100,
    annualBonusDaysTotal: 112,
    bonusMonths: [1, 3, 5, 7, 9, 11],
    bonusDailyMultiplier: 1.0,
    unionDuesDays: 1,
    unionDuesPercentFallback: 0.0333,
  },
  sanayi: {
    id: 'sanayi',
    name: 'Sanayi & Metal İş TİS',
    description: 'Ağır sanayi, metal ve fabrika TİS protokolü (4 tam maaş ikramiye, vardiya primi, yüksek bayram mesaisi)',
    year: 2025,
    minimumWageGross: 26005.50,
    sgkCeilingMultiplier: 7.5,
    sgkEmployeeRate: 0.14,
    unemploymentEmployeeRate: 0.01,
    sgkEmployerRate: 0.205,
    unemploymentEmployerRate: 0.02,
    employerIncentive5Percent: true,
    stampTaxRate: 0.00759,
    taxBrackets: [
      { limit: 158000, rate: 0.15 },
      { limit: 330000, rate: 0.20 },
      { limit: 800000, rate: 0.27 },
      { limit: 4300000, rate: 0.35 },
      { limit: Infinity, rate: 0.40 },
    ],
    foodAidDailyExemption: 240.00,
    childAidExemptionPercent: 0.04,
    familyAidExemptionPercent: 0.10,
    normalOvertimeMultiplier: 2.00,
    weekendOvertimeMultiplier: 2.50,
    holidayOvertimeMultiplier: 4.00,
    nightShiftAllowanceRate: 0.15,
    seniorityPayPerYear: 25.00,
    defaultMonthlyFuelAid: 2000,
    defaultDailyFoodAid: 250,
    defaultMonthlyTransportAid: 1750,
    defaultFamilyAidAmount: 1500,
    defaultChildAidPerChild: 500,
    defaultHygieneClothingAid: 1250,
    annualBonusDaysTotal: 120,
    bonusMonths: [3, 6, 9, 12],
    bonusDailyMultiplier: 1.0,
    unionDuesDays: 1,
    unionDuesPercentFallback: 0.0333,
  }
};

export const INITIAL_EMPLOYEE_SAMPLE: EmployeeInput = {
  tcNo: '12345678901',
  fullName: 'Ahmet Yılmaz',
  department: 'Teknik İşler & Üretim Birimi',
  jobTitle: 'Kıdemli Usta / Sendika Temsilcisi',
  startDate: '2018-04-15',
  seniorityYears: 7,
  wageType: 'daily',
  baseDailyWage: 1450.00, // Günlük brüt yevmiye
  baseMonthlyGross: 43500.00,
  workedDays: 22,
  weeklyRestDays: 4,
  paidLeaveDays: 4,
  unpaidLeaveDays: 0,
  sickLeaveDays: 0,
  totalPayableDays: 30,
  normalOvertimeHours: 12, // 12 saat normal fazla mesai
  weekendOvertimeDays: 1,  // 1 gün hafta tatili mesaisi
  holidayOvertimeDays: 1,  // 1 gün resmi tatil çalışması
  nightShiftHours: 35,     // 35 saat gece vardiyası
  hasBonusThisMonth: true, // İkramiyeli ay
  bonusDaysOverride: 15,   // 15 günlük ikramiye dilimi
  applySeniorityPay: true,
  foodAidType: 'cash',
  foodDailyAmount: 260,
  foodDays: 22,
  transportAidType: 'cash',
  transportMonthlyAmount: 1800,
  fuelAidMonthly: 1500,
  hasFamilyAid: true,
  childCount: 2,
  religiousHolidayBonus: 0,
  educationAid: 0,
  clothingSocialAid: 850,
  responsibilityRiskBonus: 1200,
  performanceBonus: 0,
  isUnionMember: true,
  unionDuesType: 'one_day',
  isBesEnrolled: true,
  courtGarnishment: 0,
  salaryAdvance: 0,
  otherPrivateDeductions: 0,
  cumulativeTaxBaseStart: 125000,
  month: 4, // Nisan
};
